version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: ${PROMETHEUS_HOSTNAME}
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - iomt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${PROMETHEUS_PORT}/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    hostname: ${GRAFANA_HOSTNAME}
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./services/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - iomt-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${GRAFANA_PORT}/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iomt-network:
    external: true

volumes:
  prometheus_data:
  grafana_data: 