version: '3.8'

services:
  postgres-database:
    image: postgres:latest
    container_name: postgres-database
    hostname: ${DATABASE_HOSTNAME}
    ports:
      - "${PG_PORT}:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iomt-network
    restart: unless-stopped

networks:
  iomt-network:
    external: true

volumes:
  postgres_data: