version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    hostname: ${REDIS_HOSTNAME}
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_MAXMEMORY=${REDIS_MAX_MEMORY}
      - REDIS_MAXCLIENTS=${REDIS_MAX_CLIENTS}
    volumes:
      - redis_data:/data
      - ./services/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - iomt-network
    restart: unless-stopped
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxclients ${REDIS_MAX_CLIENTS}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  iomt-network:
    external: true

volumes:
  redis_data: 