apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://${PROMETHEUS_HOSTNAME}:${PROMETHEUS_PORT}
    isDefault: true
    editable: true

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://${ELASTICSEARCH_HOSTNAME}:${ES_HTTP_PORT}
    database: "logs-*"
    jsonData:
      esVersion: 8.8.0
      timeField: "@timestamp"
      logMessageField: message
      logLevelField: level
    basicAuth: true
    basicAuthUser: ${ES_USERNAME}
    secureJsonData:
      basicAuthPassword: ${ES_PASSWORD}
    editable: true